title: No Bullshit Ninja
email: smfycm9k@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.nbs.ninja" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smfyhacks
github_username:  smfyhacks

# Build settings
theme: minima
plugins:
  - jekyll-feed
